### ISSUE TITLE
How to generate UDP  models from a video?

### ISSUE THREAD

**Issue by misska1** [megvii-research/CoNR#3]
How to generate UDP models from a video?

**Comment by P2Oileen** [comment]
First of all, UDP is not a model. We introduced UDP in our paper, and the definition is given in 3.3.
Regarding the generation of UDP, we recommend two methods:
1. Directly using 3D software. Since this requires 3D knowledge, we provide two samples, one with short hair and one with a double ponytail. 
As for the details: Specifically, we use MikuMikuDance to generate UDP, a software for 3D animation which needs a 3D model and an action sequence as input. Although we haven't provided an official method for this translation, there is a version written by a community author @KurisuMakise004. We have not tried it yet, but provide it for your reference: https://github.com/KurisuMakise004/MMD2UDP
2. Use the UDP detector. Although it is not detailed in the paper, we provide the code and weights. It can accept anime character images in png format and generate UDP from the images. For details, please refer to the parser `test_pose_use_parser_udp` in [train.py](https://github.com/megvii-research/CoNR/blob/main/train.py).

Coming back to your question, if you need to generate UDP from video (although we deprecate that way), you can use the second method above. First, split the video into pngs, then separate the foreground and background for each frame, take the foreground characters, and put these pngs into the same folder.
We recommend that you use these options when running train.py:
```
python -m torch.distributed.launch \
--nproc_per_node=1 train.py --mode=test \
--world_size=1 --dataloaders=2 \
--test_input_poses_images={dir_to_poses} \ # input the directory where you put the foreground pngs
--test_input_person_images={dir_to_character_sheet} \
--test_output_dir={dir_to_save_result} \
--test_checkpoint_dir={dir_to_weights} \
--test_pose_use_parser_udp=True 
```

I hope this reply can help you, and thank you for this issue!

**Comment by misska1** [comment]
Thank you very much, and I will try the second method!  ♪(･ω･)ﾉ

**Comment by misska1** [comment]
> First of all, UDP is not a model. We introduced UDP in our paper, and the definition is given in 3.3. Regarding the generation of UDP, we recommend two methods:
> 
> 1. Directly using 3D software. Since this requires 3D knowledge, we provide two samples, one with short hair and one with a double ponytail.
>    As for the details: Specifically, we use MikuMikuDance to generate UDP, a software for 3D animation which needs a 3D model and an action sequence as input. Although we haven't provided an official method for this translation, there is a version written by a community author @KurisuMakise004. We have not tried it yet, but provide it for your reference: https://github.com/KurisuMakise004/MMD2UDP
> 2. Use the UDP detector. Although it is not detailed in the paper, we provide the code and weights. It can accept anime character images in png format and generate UDP from the images. For details, please refer to the parser `test_pose_use_parser_udp` in [train.py](https://github.com/megvii-research/CoNR/blob/main/train.py).
> 
> Coming back to your question, if you need to generate UDP from video (although we deprecate that way), you can use the second method above. First, split the video into pngs, then separate the foreground and background for each frame, take the foreground characters, and put these pngs into the same folder. We recommend that you use these options when running train.py:
> 
> ```
> python -m torch.distributed.launch \
> --nproc_per_node=1 train.py --mode=test \
> --world_size=1 --dataloaders=2 \
> --test_input_poses_images={dir_to_poses} \ # input the directory where you put the foreground pngs
> --test_input_person_images={dir_to_character_sheet} \
> --test_output_dir={dir_to_save_result} \
> --test_checkpoint_dir={dir_to_weights} \
> --test_pose_use_parser_udp=True 
> ```
> 
> I hope this reply can help you, and thank you for this issue!



Hi~When I run this script:
```
python3 -m torch.distributed.launch \
--nproc_per_node=1 train.py --mode=test \
--world_size=1 --dataloaders=2 \
--test_input_poses_images=./character_sheet/ \
--test_output_udp=True \
--test_checkpoint_dir=./weights/ \
--test_output_dir=./results_udp/ \
--test_pose_use_parser_udp=True 
```
Another issue occurs:

```
batch_size: 4                                                                                                                                                                                                  [32/1197]
[['./character_sheet/0.png', './character_sheet/0.png', './character_sheet/1.png', './character_sheet/2.png', './character_sheet/3.png'], ['./character_sheet/1.png', './character_sheet/0.png', './character_sheet/1.pn
g', './character_sheet/2.png', './character_sheet/3.png'], ['./character_sheet/2.png', './character_sheet/0.png', './character_sheet/1.png', './character_sheet/2.png', './character_sheet/3.png'], ['./character_sheet/
3.png', './character_sheet/0.png', './character_sheet/1.png', './character_sheet/2.png', './character_sheet/3.png']]
---building models         
---test images:  4                                                                                          
  0%|                                                                         | 0/4 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 203, in <module>                                                                    
    test()      
  File "train.py", line 72, in test                                                                         
    infer(args, conrmodel, image_names_list)
  File "train.py", line 109, in infer                                                                       
    pred = humanflowmodel.model_step(data, training=False)
  File "/data/pengjun/motion/conr.py", line 167, in model_step                                                                                                                                                          
    pred = self.shader_pose_encoder_forward(data, pred)            
  File "/data/pengjun/motion/conr.py", line 288, in shader_pose_encoder_forward                                                                                                                                         
    _, features = self.target_pose_encoder(
  File "/data/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)                                                                   
  File "/data/pengjun/motion/model/backbone.py", line 241, in forward
    x, features = self.forward_backbone(*input)                                                             
  File "/data/pengjun/motion/model/backbone.py", line 262, in forward_backbone
    x = child(x)     
  File "/data/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 0, 4, 256, 256]
  0%|                                                                         | 0/4 [00:09<?, ?it/s]
```

**Comment by transpchan** [comment]
@misska1

It seems that I gave a wrong version to @P2Oileen. UDP detector is broken in the released version. Sorry about that.

Could you try [this one](https://github.com/transpchan/CoNR)? I have merged all her changes back.

Also note that the released UDP detector only serves as a [spoiler](https://twitter.com/transpchan/status/1543798436625104897) for the next generation of Live3D. It's not recommended to use the UDP detector at the moment. 
Try the first way if you want to customize the pose sequence.

**Comment by P2Oileen** [comment]
Hello, misska! 
Sorry for this problem; since the UDP detector is an add-on to our work, it has not been tested rigorously for the time being. I tried to modify a part of the code, and the options you use work fine for me. 
I used 3 sample character sheets as ACS input and 1 sample character sheet as pose input, and then I got these:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/26021786/182190641-8f5e4ea2-f020-4271-a8b3-74674609b31e.png"> <img width="300" alt="image" src="https://user-images.githubusercontent.com/26021786/182190569-b81e1226-234e-4a3a-93bc-894e1d571119.png">

Can you please pull it and see if this problem is solved? 
Please feel free to update any issues you have. This is very helpful for us💕

**Comment by misska1** [comment]
> Hello, misska! Sorry for this problem; since the UDP detector is an add-on to our work, it has not been tested rigorously for the time being. I tried to modify a part of the code, and the options you use work fine for me. I used 3 sample character sheets as ACS input and 1 sample character sheet as pose input, and then I got these: <img alt="image" width="250" src="https://user-images.githubusercontent.com/26021786/182190641-8f5e4ea2-f020-4271-a8b3-74674609b31e.png"> <img alt="image" width="300" src="https://user-images.githubusercontent.com/26021786/182190569-b81e1226-234e-4a3a-93bc-894e1d571119.png">
> 
> Can you please pull it and see if this problem is solved? Please feel free to update any issues you have. This is very helpful for us💕

Hi~  I successfully completedthe conversion script!
But I have a few questions:
- How to generate high-resolution  images ? By reducing the size of the color block?
- Character sheets need  pictures  without background , but videos  usually have backgrounds.Could you offer some methods to  remove the backgrounds automatically?

**Comment by transpchan** [comment]
@misska1 
* High-resolution CoNR model is not yet trained due to limited GPU memory. Try giving [me](mailto:transpchan@gmail.com) some free GPUs :)
* If I understand the question correctly, there are many existing tools for background removal. For example, Adobe Photoshop, remove.bg, etc.  You may also [try this](https://waifucutout.com) if you want one that is trained on anime images.

**Comment by P2Oileen** [comment]
Hi, misska; 
1. CoNR currently only has 256 resolution weights, we don't have weights for higher resolutions now. Some adjustments to the network may be able to adapt to higher resolutions, but we have not tried it with limited energy. Sorry for that😢
2. There are a lot of algorithms for image cut-out at present, and we also have a UDP detector version with cut-out. Still, since the UDP detector is only an add-on content of CoNR, we did not do more enhancement in it, resulting in a limited effect. To make the user experience better, only the current version without cut-out has been released.
Multi-frame matting on video is a very popular topic, and you can find a lot of work on [paperswithcode-video matting](https://paperswithcode.com/task/video-matting); As for anime images, we recommend [waifucutout](https://waifucutout.com), although it can be difficult for cutting out large amounts of images.

Thank you for your question! For some urgent problems, we will record them and try to modify them in future versions iteratively.

**Comment by misska1** [comment]
Thank you very much! I found a new paper in Image Segment Area and the demo works pretty well ~
[ECCV2022/dis-background-removal](https://huggingface.co/spaces/ECCV2022/dis-background-removal)

- How many A100 gpus did you use to train the model（256 resolution weights）, and what about  to train a bigger one?
- Do you have plans to release a commercial version?

**Comment by transpchan** [comment]
@misska1 

* Thank you for sharing the paper.  In fact, an early version of UDP detector (2020, pre-Megvii Live3D) is based on U2Net, a previous work from the same author of DIS.   It should be possible to use pretrained NNs or heuristic-based metrics as better loss function for the UDP detector. It should also be possible to train a variant of anime-segmentation model, UDP detector or CINN model with recent architectures. However, they are future work and beyond the scope of CoNRv1.
* We are [too poor](mailto:transpchan@gmail.com) to use A100.
*  Live3D starts [as a personal research project](https://github.com/transpchan/Live3D) many years ago. Although it's now supported by Megvii, I have no plan to convert it to a commercial product. It should also be noted that the MIT license allows anyone to use CoNR for commercial purposes.

**Comment by P2Oileen** [comment]
That's nice! We will try it later💕
1. As shown in 4.1 in the [paper](https://arxiv.org/pdf/2207.05378.pdf), for 128 resolution, we used 4 Nvidia 2080Ti GPUs to train for a week. We have not tried A100 yet. For the training strategy of the 256 resolution version, we will write it in the new version of the paper after confirmation.
2. As for the commercial version: Most of the authors of CoNR are researchers, so part of our purpose of open source is that developers will be free to develop any software based on it. We are also more familiar with this type of collaboration; For example, our author, Zhewei Huang's [RIFE](https://github.com/megvii-research/ECCV2022-RIFE) has several commercial software versions. We hope that CoNR can have similar opportunities, and look forward to having community authors join the development of CoNR software ☺️

**Comment by transpchan** [comment]
> For the training strategy of the 256 resolution version, we will write it in the new version of the paper after confirmation.

The same with the arxiv version, apart form that the 256 model in this repo takes three weeks without random backgrounds.  @misska1 And that's why you can't use images with background as inputs now (unlike what is stated in the arxiv).

**Comment by P2Oileen** [comment]
This issue has been solved, so we are closing it. Thanks again for your interest in CoNR~
